### ISSUE TITLE
Layout Issues at Admin Pages

### ISSUE THREAD

**Issue by shefik** [davidgewirtz/seamless-donations#2]
There are minor layout issues on the admin pages:

`/wp-admin/admin.php?page=seamless_donations_admin_addons`

This image breaks the layout, because it is too large:

`/wp-content/plugins/seamless-donations/images/extension-thank-you-enhanced-420.jpg`

Under the section `Improve Outgoing Email Reliability`, the content doesn't fit into the white box, causing the text to continue past the fixed height.

At this page:

`/wp-admin/admin.php?page=seamless_donations_admin_main`

The video is too large, and breaks the layout.

**Comment by davidgewirtz** [comment]
What's your screen size? On my 1920x1080 monitor, it looks fine. Once I know what you're looking at, I'll see what changes might be made. -- David

**Comment by shefik** [comment]
I'm viewing on a Mac laptop. See screenshot.
<img width="1134" alt="admin" src="https://cloud.githubusercontent.com/assets/274862/10562531/e2d8d68e-752d-11e5-839f-b4d5d11a776b.png">

**Comment by davidgewirtz** [comment]
I see. I've added a note to check on code responsiveness for small screens.

That said, please don't use Github for support requests. Support is available from https://wordpress.org/support/plugin/seamless-donations. Github is used for developer coordination when coding the plugin. Thanks!

--David
