### ISSUE TITLE
Update Docs to Reference PayPal Sandbox Accounts

### ISSUE THREAD

**Issue by shefik** [davidgewirtz/seamless-donations#3]
The docs should be updated to reference how to create a sandbox account at PayPal.

https://developer.paypal.com/developer/accounts

**Comment by davidgewirtz** [comment]
Here's a complete PayPal tutorial: https://youtu.be/n8z0ejIEowo

Please don't use Github issues for tech support requests. Support is available at https://wordpress.org/support/plugin/seamless-donations. Github is used only for code development and coordination.

Thanks!
